# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: GodotJS
site_url: https://godotjs.github.io
repo_url: https://github.com/godotjs/GodotJS
site_description: JS/TS language binding for Godot
extra_css:
  - css/extra.css
nav:
  - Home: index.md
  - Docs:
      - Getting Started: documentation/getting-started.md
      - Use External Editor: documentation/use-external-editor.md
      - Scripting:
          - Intro: documentation/godot-js-scripts/intro.md
          - Decorators: documentation/godot-js-scripts/decorators.md
          - Signals: documentation/godot-js-scripts/signals.md
          - NPM Dependencies: documentation/godot-js-scripts/npm-dependencies.md
          - Cyclic Imports: documentation/godot-js-scripts/cyclic-imports.md
          - Bindings: documentation/godot-js-scripts/bindings.md
          - Running code in editor: documentation/godot-js-scripts/code-in-editor.md
      - Utilities:
          - REPL: documentation/utilities/repl.md
          - SourceMaps: documentation/utilities/source-map.md
          - Statistics: documentation/utilities/statistics.md
          - Debugger: documentation/utilities/debugger.md
      - Experimental:
          - Worker: documentation/experimental/worker.md
      - Building From Source:
          - Intro: documentation/building-from-source/index.md
          - V8: documentation/building-from-source/v8.md
          - QuickJS: documentation/building-from-source/quick-js.md
          - JavaScriptCore: documentation/building-from-source/javascript-core.md
          - Web: documentation/building-from-source/web.md
  - Examples:
      - Load JSON in Singleton: examples/load-json-in-singleton.md
      - Read file local: examples/read-file-local.md
      - Use GDScript in JS or TS: examples/use-gdscript-with-godot-js.md
      - Reuse custom resources: examples/reuse-custom-resources.md
  - Development:
      - Dependencies: development/dependencies.md
      - Compiler Options: development/compiler-options.md
      - GodotJS Debugging: development/godot-js-debugging.md
      - Godot Unit Testing: development/godot-unit-testing.md
  - Misc:
      - Breaking Changes: misc/breaking-changes.md
      - Architecture: misc/architecture.md

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/godot-js.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.top
    - navigation.expand
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
